// <auto-generated />
using System;
using ElementFactory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElementFactory.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240128171730_AddedIdentityPropertiesMigration")]
    partial class AddedIdentityPropertiesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ElementFactory.Data.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasComment("Answer Class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            Value = "Втора А"
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 1,
                            Value = "Седма А"
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 1,
                            Value = "Първа А"
                        },
                        new
                        {
                            Id = 4,
                            QuestionId = 1,
                            Value = "Първа Б"
                        },
                        new
                        {
                            Id = 5,
                            QuestionId = 2,
                            Value = "Неметал"
                        },
                        new
                        {
                            Id = 6,
                            QuestionId = 2,
                            Value = "Метал"
                        },
                        new
                        {
                            Id = 7,
                            QuestionId = 2,
                            Value = "Нито едно от изброените"
                        },
                        new
                        {
                            Id = 8,
                            QuestionId = 2,
                            Value = "Алкалоземен метал"
                        },
                        new
                        {
                            Id = 9,
                            QuestionId = 3,
                            Value = "Неметали, киселини, вода"
                        },
                        new
                        {
                            Id = 10,
                            QuestionId = 3,
                            Value = "Основни оксиди, киселини, вода"
                        },
                        new
                        {
                            Id = 11,
                            QuestionId = 3,
                            Value = "Основи, киселини, метали"
                        },
                        new
                        {
                            Id = 12,
                            QuestionId = 3,
                            Value = "Киселинни оксиди, основи, соли"
                        },
                        new
                        {
                            Id = 13,
                            QuestionId = 4,
                            Value = "Na2O"
                        },
                        new
                        {
                            Id = 14,
                            QuestionId = 4,
                            Value = "Na2O + H2"
                        },
                        new
                        {
                            Id = 15,
                            QuestionId = 4,
                            Value = "NaOH + H2"
                        },
                        new
                        {
                            Id = 16,
                            QuestionId = 4,
                            Value = "NaOH + H2O"
                        },
                        new
                        {
                            Id = 17,
                            QuestionId = 5,
                            Value = "За да не взаимодейства с азота от въздуха"
                        },
                        new
                        {
                            Id = 18,
                            QuestionId = 5,
                            Value = "За да не взаимодейства с кислорода от въздуха"
                        },
                        new
                        {
                            Id = 19,
                            QuestionId = 5,
                            Value = "За да не отрови въздуха наоколо"
                        },
                        new
                        {
                            Id = 20,
                            QuestionId = 5,
                            Value = "За да не се изпари"
                        },
                        new
                        {
                            Id = 21,
                            QuestionId = 6,
                            Value = "NaCl"
                        },
                        new
                        {
                            Id = 22,
                            QuestionId = 6,
                            Value = "Na2CO3"
                        },
                        new
                        {
                            Id = 23,
                            QuestionId = 6,
                            Value = "Na2O2"
                        },
                        new
                        {
                            Id = 24,
                            QuestionId = 6,
                            Value = "NaOH"
                        },
                        new
                        {
                            Id = 25,
                            QuestionId = 7,
                            Value = "Син"
                        },
                        new
                        {
                            Id = 26,
                            QuestionId = 7,
                            Value = "Зелен"
                        },
                        new
                        {
                            Id = 27,
                            QuestionId = 7,
                            Value = "Жълт"
                        },
                        new
                        {
                            Id = 28,
                            QuestionId = 7,
                            Value = "Виолетов"
                        },
                        new
                        {
                            Id = 29,
                            QuestionId = 8,
                            Value = "NaOH"
                        },
                        new
                        {
                            Id = 30,
                            QuestionId = 8,
                            Value = "Na2O"
                        },
                        new
                        {
                            Id = 31,
                            QuestionId = 8,
                            Value = "NaCl"
                        },
                        new
                        {
                            Id = 32,
                            QuestionId = 8,
                            Value = "NaNO3"
                        },
                        new
                        {
                            Id = 33,
                            QuestionId = 9,
                            Value = "Na+ и OH-"
                        },
                        new
                        {
                            Id = 34,
                            QuestionId = 9,
                            Value = "2Na+ и OH-"
                        },
                        new
                        {
                            Id = 35,
                            QuestionId = 9,
                            Value = "Na+ и 2O-"
                        },
                        new
                        {
                            Id = 36,
                            QuestionId = 9,
                            Value = "Na+ и OH+"
                        },
                        new
                        {
                            Id = 37,
                            QuestionId = 10,
                            Value = "1"
                        },
                        new
                        {
                            Id = 38,
                            QuestionId = 10,
                            Value = "2"
                        },
                        new
                        {
                            Id = 39,
                            QuestionId = 10,
                            Value = "3"
                        },
                        new
                        {
                            Id = 40,
                            QuestionId = 10,
                            Value = "4"
                        },
                        new
                        {
                            Id = 41,
                            QuestionId = 11,
                            Value = "В червено"
                        },
                        new
                        {
                            Id = 42,
                            QuestionId = 11,
                            Value = "В малиновочервено"
                        },
                        new
                        {
                            Id = 43,
                            QuestionId = 11,
                            Value = "В синьо"
                        },
                        new
                        {
                            Id = 44,
                            QuestionId = 11,
                            Value = "В жълто"
                        },
                        new
                        {
                            Id = 45,
                            QuestionId = 12,
                            Value = "K"
                        },
                        new
                        {
                            Id = 46,
                            QuestionId = 12,
                            Value = "Li"
                        },
                        new
                        {
                            Id = 47,
                            QuestionId = 12,
                            Value = "Rb"
                        },
                        new
                        {
                            Id = 48,
                            QuestionId = 12,
                            Value = "Cs"
                        },
                        new
                        {
                            Id = 49,
                            QuestionId = 13,
                            Value = "Вярно"
                        },
                        new
                        {
                            Id = 50,
                            QuestionId = 13,
                            Value = "Грешно"
                        },
                        new
                        {
                            Id = 51,
                            QuestionId = 14,
                            Value = "Натриев хидрид"
                        },
                        new
                        {
                            Id = 52,
                            QuestionId = 14,
                            Value = "Натриев хидроксид"
                        },
                        new
                        {
                            Id = 53,
                            QuestionId = 14,
                            Value = "Натриев хидрат"
                        },
                        new
                        {
                            Id = 54,
                            QuestionId = 14,
                            Value = "Натриев хемоглобин"
                        },
                        new
                        {
                            Id = 55,
                            QuestionId = 15,
                            Value = "Приготвяне на физиологичен разтвор"
                        },
                        new
                        {
                            Id = 56,
                            QuestionId = 15,
                            Value = "Производство на сапуни"
                        },
                        new
                        {
                            Id = 57,
                            QuestionId = 15,
                            Value = "Промивка след изгаряне"
                        },
                        new
                        {
                            Id = 58,
                            QuestionId = 15,
                            Value = "Хранително-вкусова промишленост"
                        },
                        new
                        {
                            Id = 59,
                            QuestionId = 16,
                            Value = "Червено-кафяв"
                        },
                        new
                        {
                            Id = 60,
                            QuestionId = 16,
                            Value = "Виолетов"
                        },
                        new
                        {
                            Id = 61,
                            QuestionId = 16,
                            Value = "Бледосин"
                        },
                        new
                        {
                            Id = 62,
                            QuestionId = 16,
                            Value = "Жълто-зелен"
                        },
                        new
                        {
                            Id = 63,
                            QuestionId = 17,
                            Value = "H2Cl"
                        },
                        new
                        {
                            Id = 64,
                            QuestionId = 17,
                            Value = "HCl2"
                        },
                        new
                        {
                            Id = 65,
                            QuestionId = 17,
                            Value = "H2Cl2"
                        },
                        new
                        {
                            Id = 66,
                            QuestionId = 17,
                            Value = "HCl"
                        },
                        new
                        {
                            Id = 67,
                            QuestionId = 18,
                            Value = "HCl и HCl3"
                        },
                        new
                        {
                            Id = 68,
                            QuestionId = 18,
                            Value = "HCl и HClO"
                        },
                        new
                        {
                            Id = 69,
                            QuestionId = 18,
                            Value = "HCl3 и H3Cl2"
                        },
                        new
                        {
                            Id = 70,
                            QuestionId = 18,
                            Value = "HCl2 и HClO"
                        },
                        new
                        {
                            Id = 71,
                            QuestionId = 19,
                            Value = "NaCl"
                        },
                        new
                        {
                            Id = 72,
                            QuestionId = 19,
                            Value = "NaOH"
                        },
                        new
                        {
                            Id = 73,
                            QuestionId = 19,
                            Value = "H2O"
                        },
                        new
                        {
                            Id = 74,
                            QuestionId = 19,
                            Value = "H2"
                        },
                        new
                        {
                            Id = 75,
                            QuestionId = 20,
                            Value = "Натриев хлорид"
                        },
                        new
                        {
                            Id = 76,
                            QuestionId = 20,
                            Value = "Натриев хлорат"
                        },
                        new
                        {
                            Id = 77,
                            QuestionId = 20,
                            Value = "Натриев хипохлорид"
                        },
                        new
                        {
                            Id = 78,
                            QuestionId = 20,
                            Value = "Натриев хипохлорит"
                        },
                        new
                        {
                            Id = 79,
                            QuestionId = 21,
                            Value = "Осма А"
                        },
                        new
                        {
                            Id = 80,
                            QuestionId = 21,
                            Value = "Шеста А"
                        },
                        new
                        {
                            Id = 81,
                            QuestionId = 21,
                            Value = "Седма А"
                        },
                        new
                        {
                            Id = 82,
                            QuestionId = 21,
                            Value = "Пета А"
                        },
                        new
                        {
                            Id = 83,
                            QuestionId = 22,
                            Value = "Не се променя"
                        },
                        new
                        {
                            Id = 84,
                            QuestionId = 22,
                            Value = "Малиновочервен"
                        },
                        new
                        {
                            Id = 85,
                            QuestionId = 22,
                            Value = "Виолетов"
                        },
                        new
                        {
                            Id = 86,
                            QuestionId = 22,
                            Value = "Син"
                        },
                        new
                        {
                            Id = 87,
                            QuestionId = 23,
                            Value = "Сода каустик"
                        },
                        new
                        {
                            Id = 88,
                            QuestionId = 23,
                            Value = "Бертолетова сол"
                        },
                        new
                        {
                            Id = 89,
                            QuestionId = 23,
                            Value = "Готварска сол"
                        },
                        new
                        {
                            Id = 90,
                            QuestionId = 23,
                            Value = "Белина"
                        },
                        new
                        {
                            Id = 91,
                            QuestionId = 24,
                            Value = "1"
                        },
                        new
                        {
                            Id = 92,
                            QuestionId = 24,
                            Value = "2"
                        },
                        new
                        {
                            Id = 93,
                            QuestionId = 24,
                            Value = "3"
                        },
                        new
                        {
                            Id = 94,
                            QuestionId = 24,
                            Value = "4"
                        },
                        new
                        {
                            Id = 95,
                            QuestionId = 25,
                            Value = "Отрицателен със заряд 1-"
                        },
                        new
                        {
                            Id = 96,
                            QuestionId = 25,
                            Value = "Отрицателен със заряд 2-"
                        },
                        new
                        {
                            Id = 97,
                            QuestionId = 25,
                            Value = "Положителен със заряд 1+"
                        },
                        new
                        {
                            Id = 98,
                            QuestionId = 25,
                            Value = "Положителен със заряд 2+"
                        },
                        new
                        {
                            Id = 99,
                            QuestionId = 26,
                            Value = "Перхлорати"
                        },
                        new
                        {
                            Id = 100,
                            QuestionId = 26,
                            Value = "Хлорати"
                        },
                        new
                        {
                            Id = 101,
                            QuestionId = 26,
                            Value = "Хлорити"
                        },
                        new
                        {
                            Id = 102,
                            QuestionId = 26,
                            Value = "Хлориди"
                        },
                        new
                        {
                            Id = 103,
                            QuestionId = 27,
                            Value = "1"
                        },
                        new
                        {
                            Id = 104,
                            QuestionId = 27,
                            Value = "2"
                        },
                        new
                        {
                            Id = 105,
                            QuestionId = 27,
                            Value = "3"
                        },
                        new
                        {
                            Id = 106,
                            QuestionId = 27,
                            Value = "4"
                        },
                        new
                        {
                            Id = 107,
                            QuestionId = 28,
                            Value = "H + Cl"
                        },
                        new
                        {
                            Id = 108,
                            QuestionId = 28,
                            Value = "H2O + Cl2"
                        },
                        new
                        {
                            Id = 109,
                            QuestionId = 28,
                            Value = "Cl + OH"
                        },
                        new
                        {
                            Id = 110,
                            QuestionId = 28,
                            Value = "HCl + O"
                        },
                        new
                        {
                            Id = 111,
                            QuestionId = 29,
                            Value = "Вярно"
                        },
                        new
                        {
                            Id = 112,
                            QuestionId = 29,
                            Value = "Грешно"
                        },
                        new
                        {
                            Id = 113,
                            QuestionId = 30,
                            Value = "Производство на фойерверки"
                        },
                        new
                        {
                            Id = 114,
                            QuestionId = 30,
                            Value = "Дезинфекция на водите"
                        },
                        new
                        {
                            Id = 115,
                            QuestionId = 30,
                            Value = "Хранително-вкусовата промишленост"
                        },
                        new
                        {
                            Id = 116,
                            QuestionId = 30,
                            Value = "Производство на мебели"
                        },
                        new
                        {
                            Id = 117,
                            QuestionId = 31,
                            Value = "Алкален метал"
                        },
                        new
                        {
                            Id = 118,
                            QuestionId = 31,
                            Value = "Алкалоземен метал"
                        },
                        new
                        {
                            Id = 119,
                            QuestionId = 31,
                            Value = "Халоген"
                        },
                        new
                        {
                            Id = 120,
                            QuestionId = 31,
                            Value = "Преходен метал"
                        },
                        new
                        {
                            Id = 121,
                            QuestionId = 32,
                            Value = "Молекулен"
                        },
                        new
                        {
                            Id = 122,
                            QuestionId = 32,
                            Value = "Йонен"
                        },
                        new
                        {
                            Id = 123,
                            QuestionId = 32,
                            Value = "Кристален"
                        },
                        new
                        {
                            Id = 124,
                            QuestionId = 32,
                            Value = "Атомен"
                        },
                        new
                        {
                            Id = 125,
                            QuestionId = 33,
                            Value = "1"
                        },
                        new
                        {
                            Id = 126,
                            QuestionId = 33,
                            Value = "2"
                        },
                        new
                        {
                            Id = 127,
                            QuestionId = 33,
                            Value = "3"
                        },
                        new
                        {
                            Id = 128,
                            QuestionId = 33,
                            Value = "4"
                        },
                        new
                        {
                            Id = 129,
                            QuestionId = 34,
                            Value = "Гасена вар"
                        },
                        new
                        {
                            Id = 130,
                            QuestionId = 34,
                            Value = "Негасена вар"
                        },
                        new
                        {
                            Id = 131,
                            QuestionId = 34,
                            Value = "Бистра варна вода(БВВ)"
                        },
                        new
                        {
                            Id = 132,
                            QuestionId = 34,
                            Value = "Син камък"
                        },
                        new
                        {
                            Id = 133,
                            QuestionId = 35,
                            Value = "Втора А"
                        },
                        new
                        {
                            Id = 134,
                            QuestionId = 35,
                            Value = "Първа Б"
                        },
                        new
                        {
                            Id = 135,
                            QuestionId = 35,
                            Value = "Седма А"
                        },
                        new
                        {
                            Id = 136,
                            QuestionId = 35,
                            Value = "Втора Б"
                        },
                        new
                        {
                            Id = 137,
                            QuestionId = 36,
                            Value = "CaH2"
                        },
                        new
                        {
                            Id = 138,
                            QuestionId = 36,
                            Value = "CaO2"
                        },
                        new
                        {
                            Id = 139,
                            QuestionId = 36,
                            Value = "Ca(OH)2"
                        },
                        new
                        {
                            Id = 140,
                            QuestionId = 36,
                            Value = "CaO"
                        },
                        new
                        {
                            Id = 141,
                            QuestionId = 37,
                            Value = "Ca(OH)2"
                        },
                        new
                        {
                            Id = 142,
                            QuestionId = 37,
                            Value = "Ca(OH)2 и H2"
                        },
                        new
                        {
                            Id = 143,
                            QuestionId = 37,
                            Value = "CaOH и H2"
                        },
                        new
                        {
                            Id = 144,
                            QuestionId = 37,
                            Value = "CaOH"
                        },
                        new
                        {
                            Id = 145,
                            QuestionId = 38,
                            Value = "Основа"
                        },
                        new
                        {
                            Id = 146,
                            QuestionId = 38,
                            Value = "Калция не взаимодейства с киселини"
                        },
                        new
                        {
                            Id = 147,
                            QuestionId = 38,
                            Value = "Киселина"
                        },
                        new
                        {
                            Id = 148,
                            QuestionId = 38,
                            Value = "Сол"
                        },
                        new
                        {
                            Id = 149,
                            QuestionId = 39,
                            Value = "Вярно"
                        },
                        new
                        {
                            Id = 150,
                            QuestionId = 39,
                            Value = "Грешно"
                        },
                        new
                        {
                            Id = 151,
                            QuestionId = 40,
                            Value = "Киселинен"
                        },
                        new
                        {
                            Id = 152,
                            QuestionId = 40,
                            Value = "Основен"
                        },
                        new
                        {
                            Id = 153,
                            QuestionId = 40,
                            Value = "Неутрален"
                        },
                        new
                        {
                            Id = 154,
                            QuestionId = 40,
                            Value = "Смесен"
                        },
                        new
                        {
                            Id = 155,
                            QuestionId = 41,
                            Value = "CaO + H2O => CaOH + H2"
                        },
                        new
                        {
                            Id = 156,
                            QuestionId = 41,
                            Value = "Ca + 2HCl => CaCl + 2H"
                        },
                        new
                        {
                            Id = 157,
                            QuestionId = 41,
                            Value = "Ca + H2 => 2CaH"
                        },
                        new
                        {
                            Id = 158,
                            QuestionId = 41,
                            Value = "Ca + 2H2O => Ca(OH)2+H2"
                        },
                        new
                        {
                            Id = 159,
                            QuestionId = 42,
                            Value = "Вярно"
                        },
                        new
                        {
                            Id = 160,
                            QuestionId = 42,
                            Value = "Грешно"
                        },
                        new
                        {
                            Id = 161,
                            QuestionId = 43,
                            Value = "Бял"
                        },
                        new
                        {
                            Id = 162,
                            QuestionId = 43,
                            Value = "Керемиденочервен"
                        },
                        new
                        {
                            Id = 163,
                            QuestionId = 43,
                            Value = "Син"
                        },
                        new
                        {
                            Id = 164,
                            QuestionId = 43,
                            Value = "Зелен"
                        },
                        new
                        {
                            Id = 165,
                            QuestionId = 44,
                            Value = "Ca(OH)2 с вода"
                        },
                        new
                        {
                            Id = 166,
                            QuestionId = 44,
                            Value = "Ca с киселина"
                        },
                        new
                        {
                            Id = 167,
                            QuestionId = 44,
                            Value = "CaCO3 с киселина"
                        },
                        new
                        {
                            Id = 168,
                            QuestionId = 44,
                            Value = "Ca с киселинен оксид"
                        },
                        new
                        {
                            Id = 169,
                            QuestionId = 45,
                            Value = "4"
                        },
                        new
                        {
                            Id = 170,
                            QuestionId = 45,
                            Value = "7"
                        },
                        new
                        {
                            Id = 171,
                            QuestionId = 45,
                            Value = "2"
                        },
                        new
                        {
                            Id = 172,
                            QuestionId = 45,
                            Value = "11"
                        },
                        new
                        {
                            Id = 173,
                            QuestionId = 46,
                            Value = "C6H6, C6H5OH, CO3"
                        },
                        new
                        {
                            Id = 174,
                            QuestionId = 46,
                            Value = "CO2, C6H12O6, C3H5(OH)3"
                        },
                        new
                        {
                            Id = 175,
                            QuestionId = 46,
                            Value = "CO, CO2, H2CO3, Na2CO3"
                        },
                        new
                        {
                            Id = 176,
                            QuestionId = 46,
                            Value = "CO, H2CO3, C2H4(ONa)2"
                        },
                        new
                        {
                            Id = 177,
                            QuestionId = 47,
                            Value = "1"
                        },
                        new
                        {
                            Id = 178,
                            QuestionId = 47,
                            Value = "2"
                        },
                        new
                        {
                            Id = 179,
                            QuestionId = 47,
                            Value = "3"
                        },
                        new
                        {
                            Id = 180,
                            QuestionId = 47,
                            Value = "4"
                        },
                        new
                        {
                            Id = 181,
                            QuestionId = 48,
                            Value = "ВВ, които съдържат само прости връзки"
                        },
                        new
                        {
                            Id = 182,
                            QuestionId = 48,
                            Value = "ВВ, които съдържат поне една сложна връзка"
                        },
                        new
                        {
                            Id = 183,
                            QuestionId = 48,
                            Value = "ВВ с по-сложен строеж, които са циклични"
                        },
                        new
                        {
                            Id = 184,
                            QuestionId = 48,
                            Value = "ВВ, които съдържат само сложни връзки"
                        },
                        new
                        {
                            Id = 185,
                            QuestionId = 49,
                            Value = "CH4"
                        },
                        new
                        {
                            Id = 186,
                            QuestionId = 49,
                            Value = "CO2"
                        },
                        new
                        {
                            Id = 187,
                            QuestionId = 49,
                            Value = "CO"
                        },
                        new
                        {
                            Id = 188,
                            QuestionId = 49,
                            Value = "C2H2"
                        },
                        new
                        {
                            Id = 189,
                            QuestionId = 50,
                            Value = "Вярно"
                        },
                        new
                        {
                            Id = 190,
                            QuestionId = 50,
                            Value = "Грешно"
                        },
                        new
                        {
                            Id = 191,
                            QuestionId = 51,
                            Value = "Вярно"
                        },
                        new
                        {
                            Id = 192,
                            QuestionId = 51,
                            Value = "Грешно"
                        },
                        new
                        {
                            Id = 193,
                            QuestionId = 52,
                            Value = "C10H22"
                        },
                        new
                        {
                            Id = 194,
                            QuestionId = 52,
                            Value = "C9H18"
                        },
                        new
                        {
                            Id = 195,
                            QuestionId = 52,
                            Value = "C9H16"
                        },
                        new
                        {
                            Id = 196,
                            QuestionId = 52,
                            Value = "C9H20"
                        },
                        new
                        {
                            Id = 197,
                            QuestionId = 53,
                            Value = "CnH2n"
                        },
                        new
                        {
                            Id = 198,
                            QuestionId = 53,
                            Value = "CnH2n+2"
                        },
                        new
                        {
                            Id = 199,
                            QuestionId = 53,
                            Value = "CnH2n-2"
                        },
                        new
                        {
                            Id = 200,
                            QuestionId = 53,
                            Value = "CnHn"
                        },
                        new
                        {
                            Id = 201,
                            QuestionId = 54,
                            Value = "Вярно"
                        },
                        new
                        {
                            Id = 202,
                            QuestionId = 54,
                            Value = "Грешно"
                        },
                        new
                        {
                            Id = 203,
                            QuestionId = 55,
                            Value = "Температура"
                        },
                        new
                        {
                            Id = 204,
                            QuestionId = 55,
                            Value = "Налягане"
                        },
                        new
                        {
                            Id = 205,
                            QuestionId = 55,
                            Value = "Катализатор(Ni)"
                        },
                        new
                        {
                            Id = 206,
                            QuestionId = 55,
                            Value = "И трите изброени"
                        },
                        new
                        {
                            Id = 207,
                            QuestionId = 56,
                            Value = "Прости връзки"
                        },
                        new
                        {
                            Id = 208,
                            QuestionId = 56,
                            Value = "Въглеродни атоми"
                        },
                        new
                        {
                            Id = 209,
                            QuestionId = 56,
                            Value = "Водородни атоми"
                        },
                        new
                        {
                            Id = 210,
                            QuestionId = 56,
                            Value = "Сложни връзки"
                        },
                        new
                        {
                            Id = 211,
                            QuestionId = 57,
                            Value = "Бойл Мариот"
                        },
                        new
                        {
                            Id = 212,
                            QuestionId = 57,
                            Value = "Марковников"
                        },
                        new
                        {
                            Id = 213,
                            QuestionId = 57,
                            Value = "Аристотел"
                        },
                        new
                        {
                            Id = 214,
                            QuestionId = 57,
                            Value = "Менделеев"
                        },
                        new
                        {
                            Id = 215,
                            QuestionId = 58,
                            Value = "Ni"
                        },
                        new
                        {
                            Id = 216,
                            QuestionId = 58,
                            Value = "Hg2+"
                        },
                        new
                        {
                            Id = 217,
                            QuestionId = 58,
                            Value = "CCl4"
                        },
                        new
                        {
                            Id = 218,
                            QuestionId = 58,
                            Value = "Pb(CH3COO)2"
                        },
                        new
                        {
                            Id = 219,
                            QuestionId = 59,
                            Value = "Толуен и HNO3 в излишък"
                        },
                        new
                        {
                            Id = 220,
                            QuestionId = 59,
                            Value = "Фенол и HNO3"
                        },
                        new
                        {
                            Id = 221,
                            QuestionId = 59,
                            Value = "Бензен и HNO3"
                        },
                        new
                        {
                            Id = 222,
                            QuestionId = 59,
                            Value = "Бензен и нитратни соли"
                        },
                        new
                        {
                            Id = 223,
                            QuestionId = 60,
                            Value = "Ацеталдехид"
                        },
                        new
                        {
                            Id = 224,
                            QuestionId = 60,
                            Value = "Бензен и 2Na"
                        },
                        new
                        {
                            Id = 225,
                            QuestionId = 60,
                            Value = "Феноксиден анион и водороден катион"
                        },
                        new
                        {
                            Id = 226,
                            QuestionId = 60,
                            Value = "Натриев феноксид и 1/2 H2"
                        });
                });

            modelBuilder.Entity("ElementFactory.Data.Models.ChemicalElement", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("AtomicMass")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AtomicNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("AtomicRadius")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BoilingPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BulgarianState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ChemicalTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Density")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Electronegativity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ElectronicLayers")
                        .HasColumnType("int");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<bool>("IsRadioactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<decimal>("MeltingPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("YearFound")
                        .HasColumnType("int");

                    b.HasKey("Symbol");

                    b.HasIndex("ChemicalTypeId");

                    b.ToTable("ChemicalElements");

                    b.HasComment("Chemical Element Class");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.ChemicalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BulgarianName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ChemicalTypes");

                    b.HasComment("Chemical Type Class");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.Founder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Founders");

                    b.HasComment("Founder Class");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.FounderChemicalElementMap", b =>
                {
                    b.Property<int>("FounderId")
                        .HasColumnType("int");

                    b.Property<string>("ChemicalElementSymbol")
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("FounderId", "ChemicalElementSymbol");

                    b.HasIndex("ChemicalElementSymbol");

                    b.ToTable("FoundersChemicalElements");

                    b.HasComment("Founder Chemical Element Class");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RightAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasComment("Question Class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "В коя група е химичният елемент Na?",
                            RightAnswer = "Първа А"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Какво по характер е простото вещество на Na?",
                            RightAnswer = "Метал"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Натрият взаимодейства със: ",
                            RightAnswer = "Неметали, киселини и вода"
                        },
                        new
                        {
                            Id = 4,
                            Description = "При взаимодействие на Na с вода се получава:",
                            RightAnswer = "NaOH + H2"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Защо простото вещество Na се държи под петрол",
                            RightAnswer = "За да не взаимодейства с кислорода от въздуха"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Кое от химичните съединения на натрия е по-познато в практиката като сода каустик?",
                            RightAnswer = "NaOH"
                        },
                        new
                        {
                            Id = 7,
                            Description = "С какъв пламък изгаря Na?",
                            RightAnswer = "Жълт"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Кое от химичните съединения на Na се получава от реакция с реактива AgNO3?",
                            RightAnswer = "NaNO3"
                        },
                        new
                        {
                            Id = 9,
                            Description = "При електролитна дисоциация на NaOH се получават: ",
                            RightAnswer = "Na+ и OH-"
                        },
                        new
                        {
                            Id = 10,
                            Description = "От коя валентност е Na?",
                            RightAnswer = "1"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Ако в разтвор от NaOH внесем лакмус, то той се оцветява: ",
                            RightAnswer = "В синьо"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Кое от следните прости вещества има по-ниска реактивоспособност от натрия?",
                            RightAnswer = "Li"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Водният разтвор на NaOH провежда електричен ток.",
                            RightAnswer = "Вярно"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Според UPAC химичното съединение \"NaH\" се нарича:",
                            RightAnswer = "Натриев хидрид"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Кое е ГРЕШНОТО твърдение? Натрият / неговите съединения се използват за:",
                            RightAnswer = "Промивка след изгаряне"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Какъв цвят е простото вещество на Cl?",
                            RightAnswer = "Жълто-зелен"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Какво се получава при взаимодействието на хлор с водород?",
                            RightAnswer = "HCl"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Кои киселини се получават при директно взаимодействие на хлор с вода",
                            RightAnswer = "HCl и HClO"
                        },
                        new
                        {
                            Id = 19,
                            Description = "С кое от веществата хлорът НЕ взаимодейства?",
                            RightAnswer = "NaCl"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Съединението NaClO се нарича:",
                            RightAnswer = "Натриев хипохлорит"
                        },
                        new
                        {
                            Id = 21,
                            Description = "От коя група е елементът хлор?",
                            RightAnswer = "Седма А"
                        },
                        new
                        {
                            Id = 22,
                            Description = "В какъв цвят се оцветява фенолфталеина при контакт с водния разтвор на HCl?",
                            RightAnswer = "Не се променя"
                        },
                        new
                        {
                            Id = 23,
                            Description = "С какво име в практиката е известен NaClO?",
                            RightAnswer = "Белина"
                        },
                        new
                        {
                            Id = 24,
                            Description = "От колко атома се състои молекулата на хлора?",
                            RightAnswer = "2"
                        },
                        new
                        {
                            Id = 25,
                            Description = "В какъв йон се превръща атомът на хлора при реакция?",
                            RightAnswer = "Отрицателен със заряд 1-"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Как се наричат солите на хлора?",
                            RightAnswer = "Хлориди"
                        },
                        new
                        {
                            Id = 27,
                            Description = "От коя валентност е хлорът в съединението си с водорода?",
                            RightAnswer = "1"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Хипохлористата киселина се разлага до:",
                            RightAnswer = "HCl + O"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Газът хлор има силен, приятен мирис",
                            RightAnswer = "Грешно"
                        },
                        new
                        {
                            Id = 30,
                            Description = "За какво се използва хлорът в практиката?",
                            RightAnswer = "Дезинфекция на водите"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Простото вещество Ca е:",
                            RightAnswer = "Алкалоземен метал"
                        },
                        new
                        {
                            Id = 32,
                            Description = "С какъв строеж е простото вещество Ca?",
                            RightAnswer = "Кристален"
                        },
                        new
                        {
                            Id = 33,
                            Description = "С каква валентност участва в съединенията си Ca?",
                            RightAnswer = "2"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Под какво име е известно съединението CaO?",
                            RightAnswer = "Негасена вар"
                        },
                        new
                        {
                            Id = 35,
                            Description = "В коя група е Ca?",
                            RightAnswer = "Втора А"
                        },
                        new
                        {
                            Id = 36,
                            Description = "При взаимодействието на Ca с кислород се получава:",
                            RightAnswer = "CaO"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Реакцията \"Гасене на вар\" е ракция на CaO с вода, при коята се получава/т:",
                            RightAnswer = "Ca(OH)2"
                        },
                        new
                        {
                            Id = 38,
                            Description = "При взаимодействие на Ca с халогеноводородна киселина се получава:",
                            RightAnswer = "Сол"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Простото вещество Ca е газ с метален блясък и висока електропроводимост.",
                            RightAnswer = "Грешно"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Какъв характер проявява водният разтвор на калциевия дихидроксид?",
                            RightAnswer = "Основен"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Кое от следните уравнения за Ca и неговите съединения е изравнено вярно?",
                            RightAnswer = "Ca + 2H2O => Ca(OH)2+H2"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Ca се съхранява по петрол или инертен газ",
                            RightAnswer = "Вярно"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Какъв е цвета на пламъка при гореното на Ca?",
                            RightAnswer = "Керемиденочервен"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Реакцията \"Шумяща проба\" се наблюдава при взаимодействието на:",
                            RightAnswer = "CaCO3 с киселина"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Разтоворът на Ca(OH)2 е с pH:",
                            RightAnswer = "11"
                        },
                        new
                        {
                            Id = 46,
                            Description = "В кой от редовете са посочени само неорганични съединения:",
                            RightAnswer = "CO, CO2, H2CO3, Na2CO3"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Каква валентност проявява C в неговите ОС?",
                            RightAnswer = "4"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Кое е най-точното определение за ароматните ВВ?",
                            RightAnswer = "ВВ с по-сложен строеж, които са циклични"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Кое от посочените съединения е известно под името \"Газ гризу\":",
                            RightAnswer = "CH4"
                        },
                        new
                        {
                            Id = 50,
                            Description = "\"Халогенирането\" на метан е заместителна реакция.",
                            RightAnswer = "Вярно"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Всяко ОС при взаимодействие с кислород(горене) се разлага до въглероден диоксид и вода",
                            RightAnswer = "Вярно"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Кое от от следните съединения е нонан",
                            RightAnswer = "C9H20"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Каква е общата молекулна формула на алкените",
                            RightAnswer = "CnH2n"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Характерни за алкените са заместителните реакции, поради наличието на сложната двойна връзка",
                            RightAnswer = "Грешно"
                        },
                        new
                        {
                            Id = 55,
                            Description = "\"Хидрирането\" на алкени протична при наличието на:",
                            RightAnswer = "И трите изброени"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Наличието на какво се доказва с разтвор на KMnO4?",
                            RightAnswer = "Сложни връзки"
                        },
                        new
                        {
                            Id = 57,
                            Description = "При присъединяването на полярни H-съдържащи молекули към молекули на несиметрияни алкени се спазва правилото на:",
                            RightAnswer = "Марковников"
                        },
                        new
                        {
                            Id = 58,
                            Description = "За да се спре реакцията на \"Хидриране\" на алкините, така че от алкин да се получи алкен, се използва катализатор:",
                            RightAnswer = "Pb(CH3COO)2"
                        },
                        new
                        {
                            Id = 59,
                            Description = "2,4,6-тринитро толуен(TNT) се получава при взаимодействието на:",
                            RightAnswer = "Толуен и HNO3 в излишък"
                        },
                        new
                        {
                            Id = 60,
                            Description = "При взаимодействието на фенол и натрий се получава:",
                            RightAnswer = "Натриев феноксид и 1/2 H2"
                        });
                });

            modelBuilder.Entity("ElementFactory.Data.Models.QuestionTestMap", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("QuestionsTests");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 3,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 4,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 5,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 6,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 7,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 8,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 9,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 10,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 11,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 12,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 13,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 14,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 15,
                            TestId = 1
                        },
                        new
                        {
                            QuestionId = 16,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 17,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 18,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 19,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 20,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 21,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 22,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 23,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 24,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 25,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 26,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 27,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 28,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 29,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 30,
                            TestId = 2
                        },
                        new
                        {
                            QuestionId = 31,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 32,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 33,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 34,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 35,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 36,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 37,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 38,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 39,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 40,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 41,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 42,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 43,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 44,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 45,
                            TestId = 3
                        },
                        new
                        {
                            QuestionId = 46,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 47,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 48,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 49,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 50,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 51,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 52,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 53,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 54,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 55,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 56,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 57,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 58,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 59,
                            TestId = 4
                        },
                        new
                        {
                            QuestionId = 60,
                            TestId = 4
                        });
                });

            modelBuilder.Entity("ElementFactory.Data.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasComment("Test Class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "7 клас",
                            Title = "Метали. Натрий и неговите съединения"
                        },
                        new
                        {
                            Id = 2,
                            Category = "7 клас",
                            Title = "Неметали. Хлор и неговите съединения"
                        },
                        new
                        {
                            Id = 3,
                            Category = "8-9 клас",
                            Title = "Алкалоземни метали. Калций и неговите съединения"
                        },
                        new
                        {
                            Id = 4,
                            Category = "8-9 клас",
                            Title = "Органична химия. Въглерод и неговите органични съединения"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ElementFactory.Data.Models.Answer", b =>
                {
                    b.HasOne("ElementFactory.Data.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.ChemicalElement", b =>
                {
                    b.HasOne("ElementFactory.Data.Models.ChemicalType", "ChemicalType")
                        .WithMany("ChemicalElements")
                        .HasForeignKey("ChemicalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChemicalType");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.FounderChemicalElementMap", b =>
                {
                    b.HasOne("ElementFactory.Data.Models.ChemicalElement", "ChemicalElement")
                        .WithMany("FoundersChemicalElements")
                        .HasForeignKey("ChemicalElementSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElementFactory.Data.Models.Founder", "Founder")
                        .WithMany("FoundersChemicalElements")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChemicalElement");

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.QuestionTestMap", b =>
                {
                    b.HasOne("ElementFactory.Data.Models.Question", "Question")
                        .WithMany("QuestionsTests")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElementFactory.Data.Models.Test", "Test")
                        .WithMany("QuestionsTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElementFactory.Data.Models.ChemicalElement", b =>
                {
                    b.Navigation("FoundersChemicalElements");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.ChemicalType", b =>
                {
                    b.Navigation("ChemicalElements");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.Founder", b =>
                {
                    b.Navigation("FoundersChemicalElements");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("QuestionsTests");
                });

            modelBuilder.Entity("ElementFactory.Data.Models.Test", b =>
                {
                    b.Navigation("QuestionsTests");
                });
#pragma warning restore 612, 618
        }
    }
}
